version: "3.8"

services:
  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set minio http://minio:9000 user password; do
        echo 'Waiting for MinIO...'
        sleep 1
      done;
      mc mb minio/media --ignore-existing;
      "

volumes:
  minio_data:
